# -*- coding: utf-8 -*-
"""fao56.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SD1h7KlbMUw0ktOj3LvAgd6gmx13846
"""

"""
FAO-56 Penman-Monteith Reference Evapotranspiration

Author: Preminus Karani
Project: Ngao Labs AI Capstone

Reference:
Allen, R.G., Pereira, L.S., Raes, D., Smith, M.
FAO Irrigation and Drainage Paper No. 56
Crop Evapotranspiration (1998)

Units
------
Temperature : °C
Pressure    : kPa
Radiation   : MJ m^-2 day^-1
Wind Speed  : m s^-1
Latitude    : radians
Elevation   : metres
ET0         : mm day^-1
"""

import math



"""## Step A — Constants

Instead of scattering constants throughout the code:
"""

GSC = 0.0820          # MJ m^-2 min^-1

SIGMA = 4.903e-9      # Stefan-Boltzmann

ALBEDO = 0.23



"""## Step B — Atmospheric Pressure

Exactly FAO Equation 7.
"""

def atmospheric_pressure(elevation):
    """
    FAO-56 Eq.7

    Parameters
    ----------
    elevation : float
        metres above sea level

    Returns
    -------
    Atmospheric pressure (kPa)
    """

    return 101.3 * (
        ((293 - 0.0065 * elevation) / 293) ** 5.26
    )

print(atmospheric_pressure(1700))



"""## Step C — Psychrometric Constant"""

def psychrometric_constant(pressure):
    """
    FAO-56 Eq.8
    """

    return 0.000665 * pressure

P = atmospheric_pressure(1700)

print(psychrometric_constant(P))

"""## Step D — Saturation Vapour Pressure"""

def saturation_vapor_pressure(temp):
    """
    FAO-56 Eq.11
    """

    return (
        0.6108
        * math.exp(
            (17.27 * temp)
            /
            (temp + 237.3)
        )
    )

print(saturation_vapor_pressure(20))



"""## Step E_ Mean Saturation Vapour Pressure"""

def mean_saturation_vapor_pressure(
    tmax,
    tmin
):

    es_max = saturation_vapor_pressure(tmax)

    es_min = saturation_vapor_pressure(tmin)

    return (es_max + es_min) / 2

print(mean_saturation_vapor_pressure(28,18))

"""## Step F_ Actual Vapour Pressure"""

def actual_vapor_pressure(es, rh):
    """
    FAO-56 Eq.19 (using mean RH)
    """

    return es * rh / 100



"""## Step G- Slope of vapour Pressure curve"""

def slope_vapor_pressure_curve(temp):
    """
    FAO-56 Eq.13
    """

    es = saturation_vapor_pressure(temp)

    return (
        4098 * es
    ) / (
        (temp + 237.3) ** 2
    )

"""## Step H — Inverse Relative Distance Earth–Sun (FAO-56 Eq. 23)"""

def inverse_relative_distance_earth_sun(day_of_year):
    """
    FAO-56 Equation 23

    Parameters
    ----------
    day_of_year : int
        Day of the year (1-365 or 366)

    Returns
    -------
    float
        Inverse relative distance Earth-Sun (dr)
    """
    return 1 + 0.033 * math.cos((2 * math.pi / 365) * day_of_year)

"""## Step I — Solar Declination (FAO-56 Eq. 24)"""

def solar_declination(day_of_year):
    """
    FAO-56 Equation 24

    Returns
    -------
    float
        Solar declination (radians)
    """
    return 0.409 * math.sin(
        (2 * math.pi / 365) * day_of_year - 1.39
    )



"""## Step J — Sunset Hour Angle (FAO-56 Eq. 25)"""

def sunset_hour_angle(latitude, solar_decl):
    """
    FAO-56 Equation 25

    Parameters
    ----------
    latitude : float
        Latitude (radians)

    solar_decl : float
        Solar declination (radians)

    Returns
    -------
    float
        Sunset hour angle (radians)
    """
    return math.acos(
        -math.tan(latitude) * math.tan(solar_decl)
    )



"""## Step K — Extraterrestrial Radiation (FAO-56 Eq. 21)"""

def extraterrestrial_radiation(latitude, day_of_year):
    """
    FAO-56 Equation 21

    Parameters
    ----------
    latitude : float
        Latitude (radians)

    day_of_year : int

    Returns
    -------
    float
        Extraterrestrial radiation (MJ m⁻² day⁻¹)
    """
    dr = inverse_relative_distance_earth_sun(day_of_year)
    solar_decl = solar_declination(day_of_year)
    ws = sunset_hour_angle(latitude, solar_decl)

    return (
        (24 * 60 / math.pi)
        * GSC
        * dr
        * (
            ws * math.sin(latitude) * math.sin(solar_decl)
            + math.cos(latitude)
            * math.cos(solar_decl)
            * math.sin(ws)
        )
    )

"""## Step L — Daylight Hours (FAO-56 Eq. 34)"""

def daylight_hours(sunset_hour_angle):
    """
    FAO-56 Equation 34

    Parameters
    ----------
    sunset_hour_angle : float
        Sunset hour angle (radians)

    Returns
    -------
    float
        Maximum possible daylight hours
    """
    return (24 / math.pi) * sunset_hour_angle

"""## Step M — Clear Sky Radiation (FAO-56 Eq. 37)"""

def clear_sky_radiation(elevation, extraterrestrial_rad):
    """
    FAO-56 Equation 37

    Parameters
    ----------
    elevation : float
        Elevation above sea level (m)

    extraterrestrial_rad : float
        Extraterrestrial radiation (MJ m⁻² day⁻¹)

    Returns
    -------
    float
        Clear sky radiation (Rso)
    """
    return (0.75 + (2e-5 * elevation)) * extraterrestrial_rad



"""## Step M — Clear Sky Radiation (FAO-56 Eq. 37)"""

def clear_sky_radiation(elevation, extraterrestrial_rad):
    """
    FAO-56 Equation 37

    Parameters
    ----------
    elevation : float
        Elevation above sea level (m)

    extraterrestrial_rad : float
        Extraterrestrial radiation (MJ m⁻² day⁻¹)

    Returns
    -------
    float
        Clear sky radiation (Rso)
    """
    return (0.75 + (2e-5 * elevation)) * extraterrestrial_rad



"""## Step N — Solar Radiation from Sunshine Hours (Ångström–Prescott, FAO-56 Eq. 35)"""

def solar_radiation(
    daylight_hours,
    sunshine_hours,
    extraterrestrial_rad,
    a_s=0.25,
    b_s=0.50
):
    """
    FAO-56 Equation 35

    Parameters
    ----------
    daylight_hours : float
        Maximum daylight hours (N)

    sunshine_hours : float
        Actual sunshine duration (n)

    extraterrestrial_rad : float
        Extraterrestrial radiation (Ra)

    a_s : float
        Regression constant

    b_s : float
        Regression constant

    Returns
    -------
    float
        Solar radiation (Rs)
    """
    return (
        a_s +
        b_s * (sunshine_hours / daylight_hours)
    ) * extraterrestrial_rad

"""## Step O — Net Shortwave Radiation (FAO-56 Eq. 38)"""

def net_shortwave_radiation(solar_rad):
    """
    FAO-56 Equation 38

    Parameters
    ----------
    solar_rad : float
        Incoming solar radiation (Rs)
        MJ m-2 day-1

    Returns
    -------
    float
        Net shortwave radiation (Rns)
    """
    return (1 - ALBEDO) * solar_rad

"""## Step P — Net Longwave Radiation (FAO-56 Eq. 39)"""

def net_longwave_radiation(
    tmax_k,
    tmin_k,
    actual_vapor_pressure,
    solar_rad,
    clear_sky_rad
):
    """
    FAO-56 Equation 39

    Parameters
    ----------
    tmax_k : float
        Maximum temperature (Kelvin)

    tmin_k : float
        Minimum temperature (Kelvin)

    actual_vapor_pressure : float
        Actual vapour pressure (kPa)

    solar_rad : float
        Solar radiation (Rs)

    clear_sky_rad : float
        Clear sky radiation (Rso)

    Returns
    -------
    float
        Net longwave radiation (Rnl)
    """

    return (
        SIGMA
        * (
            (tmax_k**4 + tmin_k**4) / 2
        )
        * (
            0.34 - 0.14 * math.sqrt(actual_vapor_pressure)
        )
        * (
            1.35 * (solar_rad / clear_sky_rad) - 0.35
        )
    )



"""## Step Q — Net Radiation (FAO-56 Eq. 40)"""

def net_radiation(net_shortwave, net_longwave):
    """
    FAO-56 Equation 40

    Returns
    -------
    float
        Net radiation (Rn)
    """
    return net_shortwave - net_longwave



"""## R — Wind Speed at 2 m (FAO-56 Eq. 47)"""

def wind_speed_2m(wind_speed, measurement_height=2):
    """
    FAO-56 Equation 47

    Adjust wind speed to 2 m height.

    Parameters
    ----------
    wind_speed : float
        Measured wind speed (m/s)

    measurement_height : float
        Height of wind measurement (m)

    Returns
    -------
    float
        Wind speed at 2 m
    """

    if measurement_height == 2:
        return wind_speed

    return wind_speed * (
        4.87 /
        math.log(67.8 * measurement_height - 5.42)
    )

"""## Step S — Reference ET₀"""

def reference_et0(
    net_rad,
    mean_temp,
    wind_speed,
    saturation_vapor_pressure,
    actual_vapor_pressure,
    slope_vapor_pressure_curve,
    psychrometric_constant,
    soil_heat_flux=0
):
    """
    FAO-56 Penman-Monteith Equation (Daily)

    Parameters
    ----------
    net_rad : float
        Net radiation (MJ m-2 day-1)

    mean_temp : float
        Mean daily air temperature (°C)

    wind_speed : float
        Wind speed at 2 m (m/s)

    saturation_vapor_pressure : float
        Mean saturation vapour pressure (kPa)

    actual_vapor_pressure : float
        Actual vapour pressure (kPa)

    slope_vapor_pressure_curve : float
        Δ

    psychrometric_constant : float
        γ

    soil_heat_flux : float
        Daily soil heat flux (default = 0)

    Returns
    -------
    float
        Reference evapotranspiration (mm/day)
    """

    numerator = (
        0.408
        * slope_vapor_pressure_curve
        * (net_rad - soil_heat_flux)
        +
        psychrometric_constant
        * (900 / (mean_temp + 273))
        * wind_speed
        * (
            saturation_vapor_pressure
            - actual_vapor_pressure
        )
    )

    denominator = (
        slope_vapor_pressure_curve
        +
        psychrometric_constant
        * (
            1 + 0.34 * wind_speed
        )
    )

    return numerator / denominator







def calculate_daily_et0(
    Tmax,
    Tmin,
    RH,
    wind_speed,
    wind_height,
    elevation,
    latitude_deg,
    day_of_year,
    sunshine_hours,
):
    """
    Calculate daily reference evapotranspiration (ET₀)
    using the FAO-56 Penman-Monteith method.

    Parameters
    ----------
    Tmax : float
        Maximum air temperature (°C)

    Tmin : float
        Minimum air temperature (°C)

    RH : float
        Mean relative humidity (%)

    wind_speed : float
        Wind speed measured at wind_height (m/s)

    wind_height : float
        Height of wind measurement (m)

    elevation : float
        Elevation above sea level (m)

    latitude_deg : float
        Latitude in decimal degrees

    day_of_year : int
        Julian day (1-365)

    sunshine_hours : float
        Actual sunshine duration (hours)

    Returns
    -------
    float
        Daily reference evapotranspiration (mm/day)
    """

    latitude = math.radians(latitude_deg)

    Tmean = (Tmax + Tmin) / 2

    es = mean_saturation_vapor_pressure(Tmax, Tmin)
    ea = actual_vapor_pressure(es, RH)

    P = atmospheric_pressure(elevation)

    gamma = psychrometric_constant(P)

    delta = slope_vapor_pressure_curve(Tmean)

    Ra = extraterrestrial_radiation(latitude, day_of_year)

    N = daylight_hours(
        sunset_hour_angle(
            latitude,
            solar_declination(day_of_year)
        )
    )

    Rs = solar_radiation(
        sunshine_hours,
        N,
        Ra
    )

    Rso = clear_sky_radiation(
        elevation,
        Ra
    )

    Rns = net_shortwave_radiation(Rs)

    Rnl = net_longwave_radiation(
        Tmax + 273.16,
        Tmin + 273.16,
        ea,
        Rs,
        Rso
    )

    Rn = net_radiation(
        Rns,
        Rnl
    )

    u2 = wind_speed_2m(
        wind_speed,
        wind_height
    )

    G = 0

    return reference_et0(
        slope_vapor_pressure_curve=delta,
        net_rad=Rn,
        soil_heat_flux=G,
        psychrometric_constant=gamma,
        mean_temp=Tmean,
        wind_speed=u2,
        saturation_vapor_pressure=es,
        actual_vapor_pressure=ea,
    )



def calculate_daily_et0_from_radiation(
    Tmax,
    Tmin,
    RH,
    wind_speed,
    wind_height,
    elevation,
    latitude_deg,
    day_of_year,
    solar_radiation,
):
    """
    Calculate daily reference evapotranspiration (ET0)
    using measured solar radiation (Rs).

    Parameters
    ----------
    solar_radiation : float
        Incoming solar radiation (MJ/m²/day)
    """

    latitude = math.radians(latitude_deg)

    mean_temp = (Tmax + Tmin) / 2

    es = mean_saturation_vapor_pressure(Tmax, Tmin)

    ea = actual_vapor_pressure(es, RH)

    pressure = atmospheric_pressure(elevation)

    gamma = psychrometric_constant(pressure)

    delta = slope_vapor_pressure_curve(mean_temp)

    Ra = extraterrestrial_radiation(
        latitude,
        day_of_year
    )

    Rso = clear_sky_radiation(
        elevation,
        Ra
    )

    Rns = net_shortwave_radiation(
        solar_radiation
    )

    Rnl = net_longwave_radiation(
        Tmax + 273.16,
        Tmin + 273.16,
        ea,
        solar_radiation,
        Rso
    )

    Rn = net_radiation(
        Rns,
        Rnl
    )

    u2 = wind_speed_2m(
        wind_speed,
        wind_height
    )

    return reference_et0(
        slope_vapor_pressure_curve=delta,
        net_rad=Rn,
        soil_heat_flux=0,
        psychrometric_constant=gamma,
        mean_temp=mean_temp,
        wind_speed=u2,
        saturation_vapor_pressure=es,
        actual_vapor_pressure=ea,
    )